"""Restore authored motion in the presentation app without editing shared CSS.

    python app/tools/sync-motion.py          # regenerate css/motion.css
    python app/tools/sync-motion.py --check  # fail if authored motion has changed

Only animation/transition durations are copied, in index.html cascade order.
The output applies only to data-motion=full, never to data-still. No assets,
selectors, timing values or effects are invented here.
"""
import argparse
import re
from html.parser import HTMLParser
from pathlib import Path

APP = Path(__file__).resolve().parents[1]
OUT = APP / 'css/motion.css'
PREFIX = ':where(html[data-motion="full"]:not([data-still])) '


class Styles(HTMLParser):
    def __init__(self):
        super().__init__()
        self.files = []

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == 'link' and a.get('rel') == 'stylesheet':
            path = (APP / a['href']).resolve()
            if path != OUT.resolve():
                self.files.append(path)


def blocks(css):
    """Yield rule headers and balanced blocks, preserving quoted content."""
    start, opening, depth, quote, escaped = 0, None, 0, None, False
    for i, char in enumerate(css):
        if escaped:
            escaped = False
            continue
        if char == '\\':
            escaped = True
            continue
        if quote:
            if char == quote:
                quote = None
            continue
        if char in ('"', "'"):
            quote = char
        elif char == '{':
            if depth == 0:
                opening = i
            depth += 1
        elif char == '}':
            depth -= 1
            if depth == 0:
                yield css[start:opening].strip(), css[opening + 1:i]
                start = i + 1
        elif char == ';' and depth == 0:
            start = i + 1


def motion(css):
    result = []
    for selector, body in blocks(css):
        if selector.startswith('@'):
            # Reduced-motion rules are deliberately excluded for full playback.
            if selector.startswith(('@media', '@supports')) and 'prefers-reduced-motion' not in selector:
                nested = motion(body)
                if nested:
                    result.append(selector + ' {\n' + nested + '\n}')
            continue
        if 'data-still' in selector or 'data-motion' in selector:
            continue
        declarations = []
        for declaration in body.split(';'):
            name, sep, value = declaration.partition(':')
            name = name.strip()
            if sep and name in ('animation', 'transition', 'animation-duration', 'transition-duration'):
                value = re.sub(r'\s*!important\s*$', '', value.strip())
                if name in ('animation', 'transition'):
                    value = durations(value)
                    name += '-duration'
                declarations.append(name + ': ' + value + ' !important;')
        if declarations:
            # Existing motion selectors contain no comma-valued :is()/:not().
            selectors = ',\n'.join(PREFIX + s.strip() for s in selector.split(','))
            result.append(selectors + ' { ' + ' '.join(declarations) + ' }')
    return '\n'.join(result)


def durations(value):
    # Parenthesized calc()/var()/easing values stay intact. The first time in
    # each shorthand item is its duration; the second, if present, is its delay.
    tokens = re.findall(r'(?:[^\s,()]+|\((?:[^()]|\([^()]*\))*\))+|,', value)
    found, current = [], None
    for token in tokens + [',']:
        if token == ',':
            found.append(current or '0s')
            current = None
        elif current is None and (re.fullmatch(r'[\d.]+m?s', token)
                                  or token.startswith(('calc(', 'var(--t'))):
            current = token
    return ', '.join(found)


def build():
    styles = Styles()
    styles.feed((APP / 'index.html').read_text(encoding='utf-8'))
    parts = ['/* Generated by app/tools/sync-motion.py. Edit the source stylesheets, then regenerate.\n'
             '   Full presentation only; data-still and system-following pages keep their existing rules. */']
    for path in styles.files:
        css = re.sub(r'/\*.*?\*/', '', path.read_text(encoding='utf-8'), flags=re.S)
        extracted = motion(css)
        if extracted:
            parts.append('/* ' + path.relative_to(APP.parent).as_posix() + ' */\n' + extracted)
    return '\n\n'.join(parts) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = build()
    if args.check:
        ok = OUT.exists() and OUT.read_text(encoding='utf-8') == result
        print('motion CSS: ' + ('PASS' if ok else 'FAIL: run python app/tools/sync-motion.py'))
        raise SystemExit(0 if ok else 1)
    OUT.write_text(result, encoding='utf-8')
    print('Updated app/css/motion.css')
